- name: infra01
  box: centos/7
  hostname: infra01.4linux.com.br
  ipaddress: 192.168.200.10
  memory: 512
  cpus: 1

- name: infra02
  box: centos/7
  hostname: infra02.4linux.com.br
  ipaddress: 192.168.200.20
  memory: 512
  cpus: 1

- name: master01
  box: centos/7
  hostname: master01.4linux.com.br
  ipaddress: 192.168.200.30
  memory: 1024
  cpus: 1

- name: master02
  box: centos/7
  hostname: master02.4linux.com.br
  ipaddress: 192.168.200.40
  memory: 1024
  cpus: 1

- name: node01
  box: centos/7
  hostname: node01.4linux.com.br
  ipaddress: 192.168.200.50
  memory: 512
  cpus: 1

- name: node02
  box: centos/7
  hostname: node02.4linux.com.br
  ipaddress: 192.168.200.60
  memory: 512
  cpus: 1

- name: node03
  box: centos/7
  hostname: node03.4linux.com.br
  ipaddress: 192.168.200.70
  memory: 512
  cpus: 1